#!/usr/bin/env node
/**
 * Bundles the browser-side MCP Apps host (host/main.ts, which pulls in the
 * ext-apps AppBridge) into public/host.js, so the page can `import "/host.js"`
 * with no build step at run time and the package ships it as a plain file.
 *
 *   node scripts/build-host.mjs           write public/host.js
 *   node scripts/build-host.mjs --check   fail if the committed file is stale
 *                                         (part of `npm run check`)
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = fileURLToPath(new URL("..", import.meta.url));
const OUT = `${root}public/host.js`;

/** zod's classic entry re-exports every locale (~250 KB of translations) which
 *  tree-shaking can't drop. The host only needs English, which zod loads directly. */
const dropZodLocales = {
  name: "drop-zod-locales",
  setup(b) {
    b.onResolve({ filter: /locales\/index\.js$/ }, (args) =>
      args.importer.includes("/node_modules/zod/") ? { path: args.path, namespace: "empty-locales" } : undefined,
    );
    b.onLoad({ filter: /.*/, namespace: "empty-locales" }, () => ({ contents: "export {};", loader: "js" }));
  },
};

const bundle = await build({
  entryPoints: [`${root}host/main.ts`],
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "none",
  logLevel: "silent",
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [dropZodLocales],
});

const source = `// GENERATED by scripts/build-host.mjs from host/ — do not edit.\n// Regenerate with \`npm run build:host\`; \`npm run check\` fails if this is stale.\n${bundle.outputFiles[0].text}`;

if (process.argv.includes("--check")) {
  const current = await readFile(OUT, "utf8").catch(() => "");
  if (current !== source) {
    console.error("public/host.js is stale. Run: npm run build:host");
    process.exit(1);
  }
  console.log("host bundle up to date");
} else {
  await writeFile(OUT, source);
  console.log(`wrote public/host.js (${(source.length / 1024).toFixed(0)} KB)`);
}
